### ISSUE TITLE
There is an error in "The specific configuration usage"

### ISSUE THREAD

**Issue by CMDNatsu** [citizenll/godot-csv-typed-importer#2]
Firstly, congratulate you for this little asset
Secondly, It should be:
var example = preload("res://assets/example.csv")**.setup()**
Instead of:
var example = preload("res://assets/example.csv"

In the example (data.gd) of the repository is correctly typed and work properly, but I almost lose my mind for making this work.

**Comment by citizenll** [comment]
If you wish to use it this way, simply change the default value of auto_setup here to true.
https://github.com/citizenll/godot-csv-typed-importer/blob/e6998dbbd17c8e89d1623c45a19f8163fdc92a58/addons/csv-data-importer/csv_data.gd#L20

The code will work fine.
```gdscript
var example = preload("res://assets/example.csv")
var shooter = example.fetch(1)
print(shooter)
```

**Comment by CMDNatsu** [comment]
Yep absolutely, thank you very much for everything. On the other hand, I realised that the code of "csv_data.gd" that I downloaded from the godot repository is different form the one here. Please check when you have time.
This is the code from the godot repository: (I've change the .gd extension to .txt just for uploading the document)
[csv_data.txt](https://github.com/citizenll/godot-csv-typed-importer/files/14468675/csv_data.txt)

And of course you can download from here:
https://godotengine.org/asset-library/asset/1846

**Comment by citizenll** [comment]
Thank you for the reminder, the download hash for the asset library has been updated.
