### ISSUE TITLE
Additional delimiters

### ISSUE THREAD

**Issue by CMDNatsu** [citizenll/godot-csv-typed-importer#3]
Hello,

This is only an issue for European people, but the .csv files in those countries use semicolons (;) instead of commas (,) in their .csv files by default, as the decimal mark is a comma for them. As a European, take my long enough to realize that little issue that tend to slip my mind, so the script was not working properly until I realized of that. It would be nice if a new version incorporates more delimiters options.

**Comment by citizenll** [comment]
Thank you for your feedback; semicolons have been added as separators.
